ban/urls.py
from django.urls import path
from ban import views

app_name='ban'

urlpatterns = [
    path('get_banner/',views.get_banner,name='get_banner'),
    path('add_banner/',views.add_banner,name='add_banner'),
    path('edit_banner/',views.edit_banner,name='edit_banner'),

]

index/urls.py
from django.urls import path
from index import views

app_name='index'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('photo/',views.photo,name='photo'),
    path('login/',views.login,name='login'),
    path('code/',views.code,name='code'),
    path('check/',views.check,name='check'),
]

power/urls.py
from django.urls import path
from power import views
app_name = 'power'

urlpatterns = [
    path('r_login/', views.r_login, name='r_login'),
    path('check_user/', views.check_user, name='check_user'),
]

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqgrid/trirand/ui.jqgrid-bootstrap.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'jqgrid/js/i18n/grid.locale-cn.js' %}"></script>
    <script src="{% static 'jqgrid/js/jquery.jqGrid.min(1).js' %}"></script>
    <script src="{% static 'echarts/echarts.min.js' %}"></script>
    <script src="{% static 'echarts/china.js' %}"></script>
    <script src="{% static 'kindeditor/kindeditor-all-min.js' %}"></script>
    <script src="{% static 'kindeditor/lang/zh-CN.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="" class="navbar-brand">持名法州管理系统</a>
        </div>
        <div class="nav navbar-nav navbar-right ">
            <span>
                <a href="" class="text-muted">欢迎：</a>
            </span>&nbsp;&nbsp;&nbsp;&nbsp;
            <span>
                <a href="{% url 'index:login' %}" class="text-muted">登录注册</a>
            </span>
            <a href="" class="text-muted">
                <span class="glyphicon glyphicon-log-out"></span>
            </a>&nbsp;&nbsp;
        </div>
    </div>
</nav>
<div class="row">
    <div class="col-lg-2 col-sm-2 col-md-2">
        <div class="panel-group" id="action">
            <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <a href="#user" data-toggle="collapse" data-parent="#action"><h4>用户管理</h4></a>
                </div>
            </div>
            <div id="user" class="panel-collapse collapse ">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="list-group-item">
                            <a href="javascript:$('#cen').load('{% static "static_html/user_list.html" %}')">用户列表</a>
                        </li>
                        <li class="list-group-item">
                            <a href="javascript:$('#cen').load('{% static "static_html/list.html" %}')">用户注册趋势图</a>
                        </li>
                        <li class="list-group-item">
                            <a href="javascript:$('#cen').load('{% static "static_html/map.html" %}')">全国用户分布图</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <a href="#write" data-toggle="collapse" data-parent="#action"><h4>文章管理</h4></a>
                    </div>
                </div>
                <div id="write" class="panel-collapse collapse ">
                    <div class="panel-body">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="list-group-item">
                            <a href="javascript:$('#cen').load('{% static "static_html/kind.html" %}')">文章列表</a>
                        </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="panel-title">
                        <a href="#albums" data-toggle="collapse" data-parent="#action"><h4>专辑管理</h4></a>
                    </div>
                </div>
                <div id="albums" class="panel-collapse collapse ">
                    <div class="panel-body">
                        <ul class="nav nav-pills nav-stacked">
                            <li class="list-group-item">
                            <a href="javascript:$('#cen').load('{% static "static_html/album_list.html" %}')">专辑列表</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
            <div class="panel-heading">
                <div class="panel-title">
                    <a href="#img" data-toggle="collapse" data-parent="#action"><h4>轮播图管理</h4></a>
                </div>
            </div>
            <div id="img" class="panel-collapse collapse ">
                <div class="panel-body">
                    <ul class="nav nav-pills nav-stacked">
                        <li>
                            <a href="Javascript:$('#cen').load('{% static "static_html/lbo_list.html" %}')">轮播图列表</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        </div>
    </div>
    <div class="col-lg-10 col-sm-10 col-md-10" id="cen">
        <div class="jumbotron">
            <h2 class="text-muted">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;欢迎来到持名法州后台管理系统</h2>
        </div>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="{% static 'img/one.png' %}">
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <img src="{% static 'img/two.png' %}" style="width: 1707px;height: 385px">
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <img src="{% static 'img/one.png' %}">
                    <div class="carousel-caption"></div>
                </div>
                <div class="item">
                    <img src="{% static 'img/two.png' %}" style="width: 1707px;height: 385px">
                    <div class="carousel-caption"></div>
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <br/>
        <div class="panel-footer">
            <div class="panel-title">
                <h5 style="text-align: center">@百知教育 baizhi@zparkhr.com.cn</h5>
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'boot/css/bootstrap.min.css' %}">
    <script src="{% static 'boot/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'boot/js/bootstrap.min.js' %}"></script>
    <script>
        $(function () {
            $("#code").click(function () {
                $.ajax({
                    url:"{% url 'index:code' %}",
                    type:"post",
                    data:{
                        mobile:$("#mobile").val(),
                        passw:$("#passw").val(),
                    },
                    sucess:function (data) {
                        console.log(data)
                    }
                })
            })
        })
        var count = 60;
        function get_code(obj){
            var mobile = $("#mobile").val()
            if(mobile){
                if(count == 0){
                    obj.removeAttribute("disabled");
                    obj.value = "免费获取验证码";
                    count = 60;
                    return;
                }else{
                    obj.setAttribute("disabled", true);
                    obj.value = "已发送(" + count + ")";
                    count--;
                }
                setTimeout(function () {
                    get_code(obj)
                }
                , 1000)
            }else{
                alert('请输入手机号')
            }
        }
        function lgn() {

        }
    {#    function check_username() {#}
    {#    $.ajax({#}
    {#        type: "post",#}
    {#        url: "{% url 'power:check_user' %}",#}
    {#        data: $("#loginForm").serialize(),#}
    {#        success: function (data) {#}
    {#            console.log(data.status);#}
    {#            if (data.status === 1) {#}
    {#                location.href = '{% url "index:index" %}'#}
    {#            } else {#}
    {#                alert(data.msg);#}
    {#                location.reload()#}
    {#            }#}
    {#        }#}
    {#    });#}
    {##}
    {#}#}
     $(function () {
         $("#b").click(function () {
             $("#h").tab('show')
         })
     })
    </script>
</head>
<body>
<div align="center" style='background-color: #2b669a;height: 753px'>
    <div style="height: 300px;width: 400px;background: url('{% static "img/timgVW54O9UR_2yFL60v.png" %}');float: left;margin: 245px 0 0 550px">
        <div style="float: left;margin: 40px">
            <ul class="nav nav-tabs ">
                <li class="active"><a href="#o1" data-toggle="tab"><b>验证码登录</b></a></li>
                <li><a href="#o2" id="h" data-toggle="tab"><b>密码登录</b></a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="o1">
                    <form action="{% url 'index:check' %}" class="form-horizontal" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="mobile" class="col-sm-3 col-md-3 col-lg-3 control-label">手机号</label>
                            <div class="col-sm-9 col-md-9 col-lg-9">
                                <input class="form-control" id="mobile" placeholder="手机号">
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="input-group-btn">
                                <input type="button" id="code" onclick="get_code(this)" value="免费获取验证码" class="btn btn-success">
                            </span>
                        </div>
                        <div class="form-group">
                            <label for="passw" class="col-sm-3 col-md-3 col-lg-3 control-label">验证码</label>
                            <div class="col-sm-9 col-md-9 col-lg-9">
                                <input class="form-control" id="passw" placeholder="验证码" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-primary" onclick="lgn()">登录</button>
                        </div>
                    </form>
                </div>
                <div class="tab-pane" id="o2">
                    <form id="loginForm" role="form" action="{% url 'power:check_user' %}" method="post" class="form-horizontal">
                        {% csrf_token %}
                        <div class="form-group">
                        </div>
                        <div class="form-group">
                            <label for="mobile" class="col-sm-3 col-md-3 col-lg-3 control-label">手机号:</label>
                            <div class="col-sm-9 col-md-9 col-lg-9">
                                <input class="form-control" id="name" name="username" placeholder="手机号">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="basic-url" class="col-sm-3 col-md-3 col-lg-3 control-label">密码：</label>
                            <div class="col-sm-9 col-md-9 col-lg-9">
                                <input type="password" class="form-control" id="pwd" name="password" placeholder="密码">
                            </div>
                        </div>
                        <br>
                        <div class="form-group">
                            <button type="submit" class="btn btn-success" id="loginButtonId" value="登录"
                                   >登陆
                            </button>
                        </div>
{#                        <div class="form-group">#}
{#                            <button type="submit" class="btn btn-success" id="loginButtonId" value="登录"#}
{#                                    onclick="check_username()">登陆#}
{#                            </button>#}
{#                        </div>#}
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>